# Generated by Django 3.2.5 on 2022-02-08 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='标题 ')),
                ('content', mdeditor.fields.MDTextField(null=True)),
                ('flag', models.CharField(default=1, max_length=25)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('views', models.FloatField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Views_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_view_time', models.DateTimeField(auto_now_add=True)),
                ('nid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.notice')),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('phonenumber', models.CharField(blank=True, default=True, max_length=20)),
                ('signature', models.CharField(blank=True, default=True, max_length=50)),
                ('img_url', models.CharField(default=True, max_length=150, null=True)),
                ('gender', models.CharField(default=1, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'userform',
            },
        ),
        migrations.CreateModel(
            name='Leave_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.CharField(max_length=256, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='留言创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='留言最后一次修改的时间')),
                ('flag', models.CharField(default=1, max_length=25)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('message_user_username', models.CharField(default=True, max_length=25)),
                ('parent_user_username', models.CharField(default=True, max_length=25)),
                ('flag', models.CharField(default=1, max_length=25)),
                ('comment_level', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_comment', to='user.leave_message')),
                ('message_user_id', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_com_user', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_first_son', to='user.comment')),
                ('parent_user_id', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conment_first_son_user', to=settings.AUTH_USER_MODEL)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
