# Generated by Django 3.2.5 on 2022-03-10 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(max_length=256)),
                ('explanation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
                ('answerstate', models.CharField(default=0, max_length=10)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answers', to='user.question')),
            ],
        ),
    ]
