# Generated by Django 3.2.5 on 2022-03-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220311_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.examrecord'),
        ),
    ]
