# Generated by Django 3.2.5 on 2022-03-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_questions_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='e_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='q_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
