# Generated by Django 3.2.5 on 2022-03-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220312_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_url',
            new_name='references',
        ),
        migrations.RemoveField(
            model_name='question',
            name='e_url',
        ),
        migrations.CreateModel(
            name='Questiongif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_url', models.CharField(max_length=256, null=True)),
                ('qid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.question')),
            ],
        ),
        migrations.CreateModel(
            name='Questionex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_url', models.CharField(max_length=256, null=True)),
                ('qid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.question')),
            ],
        ),
    ]
