# Generated by Django 3.2.5 on 2022-03-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220313_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionex',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.question'),
        ),
        migrations.AlterField(
            model_name='questiongif',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.question'),
        ),
    ]
