# Generated by Django 3.2.5 on 2022-04-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_gread_examrecord_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrecord',
            name='grade',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
