# Generated by Django 3.2.5 on 2022-04-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_examrecord_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.answertable'),
        ),
    ]
