# Generated by Django 3.2 on 2023-02-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_question_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='picturnameandeurl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=256)),
                ('LAOpictureurl', models.CharField(max_length=256)),
                ('RAOpictureurl', models.CharField(max_length=256)),
                ('LAOjsurl', models.CharField(max_length=256)),
                ('RAOjsurl', models.CharField(max_length=256)),
            ],
        ),
    ]
