# Generated by Django 3.2 on 2023-02-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_picturnameandeurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturnameandeurl',
            name='LAOabsolutelypictureurl',
            field=models.CharField(default=11, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picturnameandeurl',
            name='RAOabsolutelypictureurl',
            field=models.CharField(default=1111, max_length=256),
            preserve_default=False,
        ),
    ]
