# Generated by Django 3.2 on 2023-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20230222_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Betainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ProgramName', models.CharField(max_length=256)),
                ('TraineeStatus', models.CharField(max_length=256)),
                ('Email', models.CharField(max_length=256)),
            ],
        ),
    ]
