# Generated by Django 3.2.9 on 2021-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AngioBaseA', '0002_auto_20211103_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('passwprd', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'userform',
            },
        ),
    ]
