# Generated by Django 3.2.9 on 2021-11-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AngioBaseA', '0004_auto_20211103_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='passwpod',
            new_name='password',
        ),
    ]
