# Generated by Django 3.2.9 on 2021-11-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AngioBaseA', '0005_rename_passwpod_userinfo_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
